spring.application.name=collector
server.port=8080

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
aggregator.kafka.sensors-topic=telemetry.sensors.v1
aggregator.kafka.hubs-topic=telemetry.hubs.v1

grpc.server.port=9090