spring.application.name=aggregator
spring.kafka.bootstrap-servers=localhost:9092
spring.main.web-application-type=none
aggregator.kafka.sensors-topic=telemetry.sensors.v1
aggregator.kafka.consume-timeout-ms=1000